---
- name: OS CHeck
  hosts: wg_vpn
  become: false

  tasks:
    - name: Base information
      ansible.builtin.debug:
        msg:
          - "Distro_Name: '{{ ansible_distribution }}'"
          - "Distro_Version: '{{ ansible_distribution_version }}'"
          - "Distro_Release: '{{ ansible_distribution_release }}'"
          - "Distro_Family: '{{ ansible_os_family }}'"

    - name: Check if OS is supported
      ansible.builtin.fail:
        msg: "I'm sorry your OS or Version has not been tested yet"
      when: >
        ansible_distribution not in ["Ubuntu", "RedHat", "CentOS", "AlmaLinux"] or
        ansible_distribution_version not in ["16.04", "18.04", "22.04", "7", "8", "9.2"]
